logFilters:
  - code: YN0060 # INCOMPATIBLE_PEER_DEPENDENCY
    level: error
  - code: YN0002 # MISSING_PEER_DEPENDENCY
    level: error
  - pattern: opensource.tophat.com@workspace:. provides react (*) with version *, which doesn't satisfy what gatsby and some of its descendants request
    level: discard

packageExtensions:
  "@parcel/types@*":
    peerDependencies:
      "@parcel/core": "*"
    peerDependenciesMeta:
      "@parcel/core":
        optional: true
  "gatsby-plugin-utils@*":
    peerDependenciesMeta:
      graphql:
        optional: true
  "@graphql-tools/graphql-tag-pluck@*":
    dependencies:
      "@babel/core": "*"
  "eslint-config-react-app@*":
    peerDependenciesMeta:
      babel-eslint:
        optional: true
