title: Top Hat Open Source Portal
description: >- # this means to ignore newlines
  Open Source at Top Hat: working to make education & technology open to the world
url: https://opensource.tophat.com
